### ISSUE TITLE
Inverted Pyramid Entrance

### ISSUE THREAD

**Issue by aerinon** [cassidoxa/ALttPEntranceRandomizer#4]
I really appreciate your hard work in making this available. You may have already fixed this, but I rolled a seed where both the North Fairy Cave and the new Inverted Pyramid Exit led to the Ganon Fall exit. Leave the Ganon area resulted in leaving the North Fairy Cave. According to the spoiler Uncle was supposed to be in the Inverted Pyramid Exit. (which I didn't even remember existed until I remember you could beat Aga1 to get up onto Hyrule Castle ledge and saw it below while I was up there)

My settings were Crossed entrances with Keysanity so Uncle was at Pyramid Hole and had Flippers. Bow was in Swamp, so I couldn't complete GT to get to that hole via Aga2. As far I could tell, it was a hard lock without knowing how to glitch through GT or glitch into swamp. I can make the spoiler log and patched rom available if needed to debug the problem further.

I cloned the repo and created the seed on June 14th and I see there are several commits since then, so maybe you already fixed it.

Thanks for your work!

**Comment by cassidoxa** [comment]
Hey Aerinon. Thanks for the feedback. I do believe this issue was fixed in one of the more recent commits, but let me know if you encounter it in the most recent.

**Comment by cassidoxa** [comment]
Went and tested it in seeds where Uncle and magic bat were in this location and it was working as intended. I'll leave this open for now pending any more reports of buggy behavior. Thanks once again and apologies for the unwinnable seed.

**Comment by aerinon** [comment]
No worries.

**Comment by aerinon** [comment]
The second seed I tried had Uncle in the same spot again and while he didn't have progression (unless you count a PoD small); it worked fine. I'm going to close this issue.
