### ISSUE TITLE
Logic seems iffy and other things

### ISSUE THREAD

**Issue by codemann8** [cassidoxa/ALttPEntranceRandomizer#5]
Overall, this was very fun even though it required the use of glitches to complete under no-gliches logic, which was a bit unexpected, but we managed to complete it anyways, we did go into it understanding this is very much alpha code.  So, I noticed a couple things, instead of opening several issues, I figured to open the one just to release my findings, and to do with it as you will.

1) Logic Issues: I did a 2-person MW Inverted Keysanity Vanilla Entrances. My LW access was locked by my own Mitts in a hammerless/flipperless PoD or my 2nd AT key which was also in the same area, to which I later found my own flippers, hammer, and both AT keys later in my own world, locked behind things my partner couldn't find without the checks I did out of logic via a Qirn bomb jump.  I could swear I checked the box to generate a Spoiler Log, but I'm not sure where it is, but I do not have a log, but if it would be helpful to see my sfc files and/or multidata file, I'd be happy to supply them.

2) Seed Generation Issues: I tried running the code from the inverted-multiworld branch, as it seemed like that contained newer changes, but I got an error: "Multiworld rom writes have not been implemented" (when I selected inverted).  So I generated a seed thru the code branch inverted-multiworld-bonta which at first gave me an error: "No such dungeon Ganons Tower for player 1".  I got this error every time as i tried to generate seeds (and I got some ROMs to output, but the error kept showing).  I didn't use any of the ROMS, I figured they were bad. I later found out that this error only shows when you try to create a spoiler log; when spoiler log is deselected, no error message.

3) Seed Adjustment Issue: When trying to apply adjustments to the ROM after generation.  I get an error: "apply_rom_settings() missing 1 required positional argument: 'names'"  I did supply player names on the initial generation, but left the adjustment blank.  But I also tried to re-enter names in the adjustment, but it still gave this error.  Using the master branch GUI, I was able to adjust the ROM appropriately.

4) Bomb-Wall Entrances: Soft-lock possibility exists when entering entrances that can be bombed from the inside, ie TR Laser Bridge entrance.  Upon entering, the character will be stuck inside the wall to where you have to lay a bomb to continue. If you don't have any bombs or have extreme low health, it could result in a soft-lock situation.

Overall, I'm very happy this mode is coming along and making it's way into MW, we both had fun running it.  I'd be happy to run further tests on future versions and provide you any information that would prove useful to determining what went wrong on the logic.

**Comment by codemann8** [comment]
I amend my statement for (2) above, I got that Ganons Tower error message only when attempting to create a spoiler log.  No spoiler log, no error message.  I edited the above comment to reflect that.

**Comment by cassidoxa** [comment]
Hey codemann8, thanks for the feedback. The inverted-multiworld branch is my fork of the main ER dev branch which is implementing ROM writes and client/server stuff differently. The TR doors, spoiler logs, and adjuster should be fixed. I'm not sure about the logic. Bonta has a balancing algorithm that re-shuffles some items and I haven't looked at it too closely. 

If you could send me a seed number or spoiler log for any problematic games you generate, I'll take a look at them. I think the seed number from the generation you mentioned should give me the same configuration.

**Comment by codemann8** [comment]
@cassidoxa Our seed number was 916282908. It's entirely possible we just missed something (thru a convoluted progression trail), but we're quite certain that wasn't the case.

**Comment by cassidoxa** [comment]
Thanks, and how many worlds did you generate?

**Comment by codemann8** [comment]
@cassidoxa I did 2 worlds, but you should take note what I said in (2), I was forced to use the bonta branch, instead of your other one.

**Comment by cassidoxa** [comment]
Thanks. The other branch can't generate multiworld ROMs at all; the bonta branch is the intended one for inverted multi. I took a look at the playthrough and it does seem to think you can get to PoD when you can't. I think I found the issue where the Old Man Cave isn't connected to the proper region. The next commit should fix it.

Thanks a lot for pointing this out by the way. I probably wouldn't have noticed for awhile.

**Comment by cassidoxa** [comment]
I tested the spoilers and GUI adjuster and they seem to be working. The playthroughs for vanilla shuffle seem correct as well. The randomizer no longer thinks you can reach East Dark World by entering and exiting Old Man Cave. I'll leave this open for a bit pending any more reports of buggy behavior.
