### ISSUE TITLE
Problem genning a rom.

### ISSUE THREAD

**Issue by Darkrid1998** [cassidoxa/ALttPEntranceRandomizer#6]
Every time my friend or I gen an inverted MW rom, we get "No such region Agahnims Tower for player 1." Not particularly sure *why* this is happening.

**Comment by codemann8** [comment]
I was getting a similar error when trying to generate a ROM with a spoiler log.  Try generating a seed without a spoiler log to try to advance further while @cassidoxa has a chance to look into it.

**Comment by Darkrid1998** [comment]
Yeah I tried that, neither worked, gave the same exact error.

**Comment by codemann8** [comment]
I'm also not sure which branch you are grabbing the code from. It isn't clear from the GitHub page, but you should make sure you are using the code from the inverted-multiworld-bonta branch, not master.

https://github.com/cassidoxa/ALttPEntranceRandomizer/tree/inverted-multiworld-bonta

**Comment by Darkrid1998** [comment]
Yeah we were using that branch.

**Comment by cassidoxa** [comment]
Are you using the latest code from that branch? It's been updated since I posted it in the discord. Also what settings are you trying to generate a seed with?

**Comment by Darkrid1998** [comment]
As far as I know I'm on the latest one, I've redownloaded the code recently. My settings are: All Dungeons, Keysanity, progressive equipment random, Entrance shuffle Vanilla, Include Ganon's Tower and Pyramid Hole in shuffle pool, Enemizer and Normal boss shuffle.

**Comment by cassidoxa** [comment]
Thanks. I believe this is an enemizer issue, but I'm not sure why it's affecting Agahnim's Tower. I'll see if I can figure it out.

**Comment by cassidoxa** [comment]
I've fixed an enemizer bug related to Ganons Tower but not Aga Tower. I'm not sure if it will work yet; I'm not on my WIndows machine to test it. But feel free to give it another shot.

**Comment by cassidoxa** [comment]
Ok, I've got it in a state where it can generate ROMs with enemizer on. Make sure you don't check the "create spoilers" option as well.
