### ISSUE TITLE
Seeming logic error in inverted multiworld

### ISSUE THREAD

**Issue by Klariodon** [cassidoxa/ALttPEntranceRandomizer#8]
I was playing an inverted multiworld with some friends earlier today, but we ended up getting stuck and consulting the spoiler log. Player 4 was intended to get light world access in sphere 4, despite not having the items required for it. I've included the spoiler log.
[ER_noglitches_normal-inverted-dungeons_vanilla-balanced-keysanity-prog_random_731640868_Spoiler.txt](https://github.com/cassidoxa/ALttPEntranceRandomizer/files/3562525/ER_noglitches_normal-inverted-dungeons_vanilla-balanced-keysanity-prog_random_731640868_Spoiler.txt)

**Comment by cassidoxa** [comment]
Thanks for the report. I had accidentally mixed up which Death Mountain Return Cave entrance was which, and the game thought the main Light World Area could be reached via the return cave entrance on Death Mountain. Will be pushing a fix shortly.
